# Generated by Django 2.0 on 2018-02-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaplatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(default=0)),
                ('response', models.CharField(max_length=1)),
                ('correct_resp', models.CharField(max_length=1)),
                ('sess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaplatform.Session')),
            ],
        ),
    ]
