# Generated by Django 2.0 on 2018-02-03 07:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qaplatform', '0002_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Sess',
        ),
    ]
