# Generated by Django 2.0 on 2017-12-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20171224_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/img/default.jpg', upload_to='static/img/photo'),
        ),
    ]
