# Generated by Django 2.0 on 2017-12-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dislikes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
