# Generated by Django 2.0 on 2018-02-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'base_manager_name': 'objects'},
        ),
    ]
